# Translation of Odoo Server.
# This file contains the translation of the following modules:
# 	* muztorg_base_import_customization
#
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server 14.0\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-08-10 18:16+0000\n"
"PO-Revision-Date: 2023-08-10 21:23+0300\n"
"Last-Translator: \n"
"Language-Team: \n"
"Language: ru\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n"
"%10<=4 && (n%100<12 || n%100>14) ? 1 : 2);\n"
"X-Generator: Poedit 3.3.2\n"

#. module: muztorg_base_import_customization
#: model:ir.model,name:muztorg_base_import_customization.model_base
msgid "Base"
msgstr "Базовый"

#. module: muztorg_base_import_customization
#: model:ir.model,name:muztorg_base_import_customization.model_base_import_import
msgid "Base Import"
msgstr "Базовый импорт"

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/ir_fields.py:0
#, python-format
msgid ""
"Cannot create new '%s' records from their name alone. Please create those "
"records manually and try importing again."
msgstr ""
"Невозможно создать новые записи '%s' только по их имени. Создайте эти "
"записи вручную и повторите попытку импорта."

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/base_import.py:0
#, python-format
msgid "Control Code"
msgstr "Контрольный код"

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/base_import.py:0
#, python-format
msgid "Database ID"
msgstr "ИД Базы данных"

#. module: muztorg_base_import_customization
#: model:ir.model.fields,field_description:muztorg_base_import_customization.field_base_import_import__display_name
#: model:ir.model.fields,field_description:muztorg_base_import_customization.field_ir_fields_converter__display_name
msgid "Display Name"
msgstr "Отображаемое название"

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/base_import.py:0
#, python-format
msgid "External ID"
msgstr "Внешний ID"

#. module: muztorg_base_import_customization
#: model:ir.model,name:muztorg_base_import_customization.model_ir_fields_converter
msgid "Fields Converter"
msgstr "Конвертер строк"

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/base_model.py:0
#, python-format
msgid ""
"Found more than 10 errors and more than one error per 10 records, "
"interrupted to avoid showing too many errors."
msgstr ""
"Найдено более 10 ошибок и более одной ошибки на 10 записей, прервано, "
"чтобы не показывать слишком много ошибок."

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/base_model.py:0
#, python-format
msgid "Found multiple matches for control code '%s' (%d matches)"
msgstr ""
"Найдено несколько совпадений для контрольного кода '%s' (совпадений: %d)"

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/ir_fields.py:0
#, python-format
msgid "Found multiple matches for field '%%(field)s' (%d matches)"
msgstr "Найдено несколько совпадений для поля '%%(field)s' (%d совпадений)"

#. module: muztorg_base_import_customization
#: model:ir.model.fields,field_description:muztorg_base_import_customization.field_base_import_import__id
#: model:ir.model.fields,field_description:muztorg_base_import_customization.field_ir_fields_converter__id
msgid "ID"
msgstr "ID"

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/ir_fields.py:0
#, python-format
msgid "Invalid database id '%s' for the field '%%(field)s'"
msgstr "Неверный идентификатор базы данных \"%s\" для поля \"%%(поле)s\""

#. module: muztorg_base_import_customization
#: model:ir.model.fields,field_description:muztorg_base_import_customization.field_base_import_import____last_update
#: model:ir.model.fields,field_description:muztorg_base_import_customization.field_ir_fields_converter____last_update
msgid "Last Modified on"
msgstr "Последнее изменение в"

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/ir_fields.py:0
#, python-format
msgid ""
"No matching record found for %(field_type)s '%(value)s' in field "
"'%%(field)s'"
msgstr ""
"Не найдена соответствующая запись для %(field_type)s '%(value)s' в поле "
"'%%(field)s'"

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/ir_fields.py:0
#, python-format
msgid ""
"No matching record found for %(field_type)s '%(value)s' in field "
"'%%(field)s' and the following error was encountered when we attempted to "
"create one: %(error_message)s"
msgstr ""
"Не найдено соответствующей записи для %(field_type)s '%(value)s' в поле "
"'%%(field)s' и при попытке создать запись произошла следующая ошибка: "
"%(error_message)s"

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/ir_fields.py:0
#, python-format
msgid ""
"Product with control code '%s' was not found. Please create those records "
"manually and try importing again."
msgstr ""
"Продукт с контрольным кодом '%s' не найден. Создайте эти записи вручную и "
"повторите попытку импорта."

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/base_model.py:0
#, python-format
msgid "Resolve other errors first"
msgstr "Сначала устраните другие ошибки"

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/ir_fields.py:0
#, python-format
msgid "See all possible values"
msgstr "Посмотреть все возможные значения"

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/base_model.py:0
#, python-format
msgid "Unknown database error: '%s'"
msgstr "Неизвестная ошибка базы данных: '%s'"

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/base_model.py:0
#, python-format
msgid "Unknown database identifier '%s'"
msgstr "Неизвестный идентификатор базы данных '%s'"

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/base_model.py:0
#, python-format
msgid "Unknown error during import:"
msgstr "Неизвестная ошибка при импорте:"

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/ir_fields.py:0
#, python-format
msgid "Unknown sub-field '%s'"
msgstr "Неизвестное подполе '%s'"

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/ir_fields.py:0
#, python-format
msgid "control code"
msgstr "контрольный код"

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/ir_fields.py:0
#, python-format
msgid "database id"
msgstr "идентификатор базы данных"

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/ir_fields.py:0
#, python-format
msgid "external id"
msgstr "внешний идентификатор"

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/ir_fields.py:0
#, python-format
msgid "name"
msgstr "название"
