# Translation of Odoo Server.
# This file contains the translation of the following modules:
# 	* muztorg_base_import_customization
#
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server 14.0\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-08-10 18:17+0000\n"
"PO-Revision-Date: 2023-08-10 21:29+0300\n"
"Last-Translator: \n"
"Language-Team: \n"
"Language: uk_UA\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n"
"%10<=4 && (n%100<12 || n%100>14) ? 1 : 2);\n"
"X-Generator: Poedit 3.3.2\n"

#. module: muztorg_base_import_customization
#: model:ir.model,name:muztorg_base_import_customization.model_base
msgid "Base"
msgstr "Базовий"

#. module: muztorg_base_import_customization
#: model:ir.model,name:muztorg_base_import_customization.model_base_import_import
msgid "Base Import"
msgstr "Базовий імпорт"

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/ir_fields.py:0
#, python-format
msgid ""
"Cannot create new '%s' records from their name alone. Please create those "
"records manually and try importing again."
msgstr ""
"Неможливо створити нові записи '%s' лише з їх імені. Створіть ці записи "
"вручну та спробуйте імпортувати знову."

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/base_import.py:0
#, python-format
msgid "Control Code"
msgstr "Контрольний код"

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/base_import.py:0
#, python-format
msgid "Database ID"
msgstr "Ідентифікатор бази даних"

#. module: muztorg_base_import_customization
#: model:ir.model.fields,field_description:muztorg_base_import_customization.field_base_import_import__display_name
#: model:ir.model.fields,field_description:muztorg_base_import_customization.field_ir_fields_converter__display_name
msgid "Display Name"
msgstr "Відображувана назва"

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/base_import.py:0
#, python-format
msgid "External ID"
msgstr "Зовнішній ідентифікатор"

#. module: muztorg_base_import_customization
#: model:ir.model,name:muztorg_base_import_customization.model_ir_fields_converter
msgid "Fields Converter"
msgstr "Конвертер рядків"

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/base_model.py:0
#, python-format
msgid ""
"Found more than 10 errors and more than one error per 10 records, "
"interrupted to avoid showing too many errors."
msgstr ""
"Знайдено понад 10 помилок і більше однієї помилки на 10 записів, "
"перервано, щоб уникнути показу великої кількості помилок."

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/base_model.py:0
#, python-format
msgid "Found multiple matches for control code '%s' (%d matches)"
msgstr "Знайдено кілька збігів для контрольного коду '%s' (%d збігів)"

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/ir_fields.py:0
#, python-format
msgid "Found multiple matches for field '%%(field)s' (%d matches)"
msgstr "Знайдено кілька збігів для поля '%%(field)s' (%d збігів)"

#. module: muztorg_base_import_customization
#: model:ir.model.fields,field_description:muztorg_base_import_customization.field_base_import_import__id
#: model:ir.model.fields,field_description:muztorg_base_import_customization.field_ir_fields_converter__id
msgid "ID"
msgstr "ID"

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/ir_fields.py:0
#, python-format
msgid "Invalid database id '%s' for the field '%%(field)s'"
msgstr "Помилковий ідентифікатор бази даних '%s' для поля '%%(field)s'"

#. module: muztorg_base_import_customization
#: model:ir.model.fields,field_description:muztorg_base_import_customization.field_base_import_import____last_update
#: model:ir.model.fields,field_description:muztorg_base_import_customization.field_ir_fields_converter____last_update
msgid "Last Modified on"
msgstr "Останні зміни на"

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/ir_fields.py:0
#, python-format
msgid ""
"No matching record found for %(field_type)s '%(value)s' in field "
"'%%(field)s'"
msgstr ""
"Не знайдено відповідного запису для %(field_type)s '%(value)s' у полі "
"'%%(field)s'"

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/ir_fields.py:0
#, python-format
msgid ""
"No matching record found for %(field_type)s '%(value)s' in field "
"'%%(field)s' and the following error was encountered when we attempted to "
"create one: %(error_message)s"
msgstr ""
"Не знайдено жодного відповідного запису для %(field_type)s '%(value)s' у "
"полі '%%(field)s' та під час спроби його створення сталася така помилка: "
"%(error_message)s"

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/ir_fields.py:0
#, python-format
msgid ""
"Product with control code '%s' was not found. Please create those records "
"manually and try importing again."
msgstr ""
"Продукт із контрольним кодом '%s' не знайдено. Створіть ці записи вручну "
"та спробуйте імпортувати знову."

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/base_model.py:0
#, python-format
msgid "Resolve other errors first"
msgstr "Спочатку виправте інші помилки"

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/ir_fields.py:0
#, python-format
msgid "See all possible values"
msgstr "Переглянути всі можливі значення"

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/base_model.py:0
#, python-format
msgid "Unknown database error: '%s'"
msgstr "Невідома помилка бази даних: '%s'"

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/base_model.py:0
#, python-format
msgid "Unknown database identifier '%s'"
msgstr "Невідомий ідентифікатор бази даних '%s'"

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/base_model.py:0
#, python-format
msgid "Unknown error during import:"
msgstr "Невідома помилка під час імпорту:"

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/ir_fields.py:0
#, python-format
msgid "Unknown sub-field '%s'"
msgstr "Невідоме підполе '%s'"

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/ir_fields.py:0
#, python-format
msgid "control code"
msgstr "контрольний код"

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/ir_fields.py:0
#, python-format
msgid "database id"
msgstr "ідентифікатор бази даних"

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/ir_fields.py:0
#, python-format
msgid "external id"
msgstr "зовнішній ідентифікатор"

#. module: muztorg_base_import_customization
#: code:addons/muztorg_base_import_customization/models/ir_fields.py:0
#, python-format
msgid "name"
msgstr "назва"
